export const LOCALSTORAGE_KEY = 'aoem_mge_calc';

export const ROUTES = {
    HOME: '/',
    ADMIN: '/admin',
    ERROR: '/*'
}

export const TRIBE_LEVEL_MULTIPLIERS = {
    'Level 1-4': 50,
    'Level 5-8': 80,
    'Level 9-12': 100,
    'Level 13-16': 150,
    'Level 17-20': 180,
    'Level 21-24': 220,
    'Level 25-28': 260,
    'Level 29-30': 300,
}

export const DAY_KEYS = {
    DAY_ONE: 'dayOne',
    DAY_TWO: 'dayTwo', 
    DAY_THREE: 'dayThree',
    DAY_FOUR:  'dayFour',
    DAY_FIVE: 'dayFive',
    DAY_SIX: 'daySix',
    DAY_SEVEN: 'daySeven'
}
export const POINTS_AND_MULTIPLIERS = {
    STAMINA_PER_TRIBE: 5,
    STAMINA_DAILY_BOOST: 50,
    STAMINA_DAILY_PREV: 45, 
    LEGENDARY_GEAR: 30000, 
    EPIC_MEDAL: 500,
    LEGENDARY_MEDAL: 2500, 
    EPIC_SCROLL: 350,
    LEGENDARY_SCROLL: 2500,
    RESOURCE_DIVIDER: 100,
    RESOURCE_POINT: 1, 
    FIVE_SPIN_COST: 4200,
    SINGLE_SPIN_COST: 900,
    SPEED_UP_MULTIPLIER: 30,
    FINE_CRAFT: 2000,
    COPPER_SAND: 400,
    SILVER_SAND: 1000,
    FINE_GOLD: 3000,
    METEOR_STEEL: 20000,
    LEVEL_ONE_MULTIPLIER: 2,
    LEVEL_TWO_MULTIPLIER: 3,
    LEVEL_THREE_MULTIPLIER: 5,
    LEVEL_FOUR_MULTIPLIER: 10,
    LEVEL_FIVE_MULTIPLIER: 20,
    LEVEL_SIX_MULTIPLIER: 50,
    LEVEL_SEVEN_MULTIPLIER: 100,
    LEVEL_GAP_MULTIPLIER: 1,
    BUILDING_MULTIPLIER: 3,
    RESEARCH_MULTIPLIER: 6,
    TRAINING_MULTIPLIER: 3
}


